# Generated by Django 4.0.2 on 2022-02-17 10:23

from django.db import migrations, models
import django.db.models.deletion
import gridfs_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_name", models.CharField(max_length=30)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, storage=gridfs_storage.storage.GridFSStorage(base_url="/"), upload_to=""
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "ordering": ["contact_name"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[("phone", "phone"), ("telegram", "telegram"), ("skype", "skype"), ("email", "email")],
                        default="phone",
                        max_length=20,
                    ),
                ),
                ("info", models.CharField(max_length=30)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_methods",
                        to="phone_book_app.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication method",
                "verbose_name_plural": "Communication methods",
            },
        ),
    ]
