# Generated by Django 4.0.1 on 2022-01-26 10:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunicationMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("communication_name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Communication method",
                "verbose_name_plural": "Communication methods",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_name", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "avatar",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(location="/media/avatars"), upload_to=""
                    ),
                ),
                ("communication_method", models.ManyToManyField(to="phone_book_app.CommunicationMethod")),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "ordering": ["contact_name"],
            },
        ),
    ]
