# Generated by Django 4.0.1 on 2022-01-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone_book_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="communication_method",
            field=models.ManyToManyField(blank=True, to="phone_book_app.CommunicationMethod"),
        ),
    ]
